In [13]:
df = np.array(df)
print(df)

[[3.17966504 3.03062471 3.22275227 ... 3.70514307 3.92179743 3.5667659 ]
 [3.31315547 3.12753458 3.36718872 ... 3.00232446 3.48703507 3.75358101]
 [3.5318474  3.55448902 3.44163644 ... 3.53159902 3.77334177 3.25474063]
 ...
 [3.55076635 3.48014853 3.65358394 ... 2.69928466 0.9630304  3.1252519 ]
 [3.64113611 3.67916051 3.13758092 ... 4.34764293 3.85532063 3.21161165]
 [3.58635986 2.83222446 3.24274907 ... 2.69928466 0.73012916 3.04170596]]


In [16]:

import numpy as np
from sklearn.linear_model import LinearRegression, LassoLarsIC
import pandas as pd

df = pd.read_csv("a1_data.csv")
df = np.array(df)
print(df)


def sortnregress(X):
    """ Take n x d data, order nodes by marginal variance and
    regresses each node onto those with lower variance, using
    edge coefficients as structure estimates. """
    # print(X)
    LR = LinearRegression()
    LL = LassoLarsIC(criterion='bic')

    d = X.shape[1]
    # print(d)
    W = np.zeros((d, d))
    # print(W)
    increasing = np.argsort(np.var(X, axis=0))
    for k in range(1, d):
        covariates = increasing[:k]
        target = increasing[k]

        LR.fit(X[:, covariates], X[:, target].ravel())
        weight = np.abs(LR.coef_)
        LL.fit(X[:, covariates] * weight, X[:, target].ravel())
        W[covariates, target] = LL.coef_ * weight

    return W

output = sortnregress(df)


[[3.17966504 3.03062471 3.22275227 ... 3.70514307 3.92179743 3.5667659 ]
 [3.31315547 3.12753458 3.36718872 ... 3.00232446 3.48703507 3.75358101]
 [3.5318474  3.55448902 3.44163644 ... 3.53159902 3.77334177 3.25474063]
 ...
 [3.55076635 3.48014853 3.65358394 ... 2.69928466 0.9630304  3.1252519 ]
 [3.64113611 3.67916051 3.13758092 ... 4.34764293 3.85532063 3.21161165]
 [3.58635986 2.83222446 3.24274907 ... 2.69928466 0.73012916 3.04170596]]


In [17]:
pd.DataFrame(output)

0    1         2         3         4         5         6         7   \
0   0.000000  0.0  0.192736  0.000000  0.000000  0.000000 -0.190650  0.081409   
1   0.783546  0.0 -0.190552  0.062237  0.000000  0.017826  0.232770  0.000000   
2   0.000000  0.0  0.000000  0.131269  0.161558  0.000000 -0.065559  0.000000   
3   0.000000  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4   0.000000  0.0  0.000000  0.248685  0.000000  0.023572  0.000000  0.000000   
5   0.000000  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
6   0.000000  0.0  0.000000  0.000000  0.000000  0.995549  0.000000  0.000000   
7   0.000000  0.0  0.000000  0.000000  0.145174  0.068977  0.303719  0.000000   
8   0.000000  0.0  0.000000  0.000000  0.000000  0.000000 -0.036843  0.000000   
9   0.000000  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
10  0.000000  0.0  0.000000  0.000000  0.042721  0.035587 -0.078033  0.000000   

         8         9         10  
0  -0.07473 -0.443256 -0.175403  
1   0.13097  0.498711  0.146622  
2   0.00000  0.000000 -0.032207  
3   0.00000 -0.032294  0.000000  
4   0.00000  0.033448  0.000000  
5   0.00000  0.226411  0.000000  
6   0.00000  0.000000  0.000000  
7   0.16958 -0.302512  0.075125  
8   0.00000  0.751465  0.197669  
9   0.00000  0.000000  0.000000  
10  0.00000  0.000000  0.000000